#pragma once

#include <cstdint>

#include "absl/status/statusor.h"
#include "src/cuda/buffer.h"
#include "src/cuda/executor.h"

namespace pluto::weight_analysis {

// Invalid rows must never be counted as correctly predicted tokens.
inline constexpr int32_t kInvalidTokenId = -1;

// Queues one minimum-ID argmax per row of contiguous FP32 logits on executor.
// The returned device buffer contains int32_t[rows]. Shape/executor errors are
// returned synchronously; CUDA execution and numerical checks are asynchronous.
// A row containing ANY NaN or infinity in its logical vocabulary returns -1.
// Padding columns are ignored, even when they contain NaNs or larger values.
// Callers must reject -1 after copying IDs to page-locked host memory and
// synchronizing. The logits are never modified and are not copied to the host.
//
// This storage contract is independent of model activation/compute dtype: the
// current tied LM head produces FP32 logits even for a BF16 model. Do not pass
// packed FP16/BF16/FP8 activation buffers to this function.
//
// Validation use: under deterministic causal decoding, argmax agreement with
// teacher-forced target tokens UNTIL THE FIRST MISMATCH gives the greedy
// matched-prefix length. Agreement after that mismatch is not a continuation
// generated by the model and must not be counted as exact free-running recall.
absl::StatusOr<cuda::Buffer> ArgmaxTokens(cuda::Executor& executor,
                                          const cuda::Buffer& logits, int rows,
                                          int logical_vocab_size,
                                          int padded_vocab_size);

}  // namespace pluto::weight_analysis
