load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("@rules_cuda//cuda:defs.bzl", "cuda_library")

cc_library(
    name = "dataset",
    srcs = ["dataset.cc"],
    hdrs = ["dataset.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/dataset:dataset",
        "//src/dataset:tokenizer",
        "//src/util:status_macros",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/memory",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/types:span",
        "@cuda//:cuda_runtime",
    ],
)

cc_test(
    name = "dataset_test",
    size = "small",
    srcs = ["dataset_test.cc"],
    data = ["//testdata:general_facts_dataset.txt"],
    tags = ["requires-gpu"],
    deps = [
        ":dataset",
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/dataset:dataset",
        "//src/dataset:gpt2_tokenizer",
        "//src/dataset:plain_text_tokenizer",
        "//src/dataset:tokenizer",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
        "@cuda//:cuda_runtime",
        "@googletest//:gtest_main",
    ],
)

cuda_library(
    name = "predictions",
    srcs = ["predictions.cc"],
    hdrs = ["predictions.h"],
    copts = ["-std=c++20"],
    host_copts = ["-std=c++20"],
    deps = [
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/util:status_macros",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@cuda//:cuda_runtime",
    ],
)

cc_test(
    name = "predictions_test",
    srcs = ["predictions_test.cc"],
    tags = ["requires-gpu"],
    deps = [
        ":predictions",
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/llm:layer",
        "//src/llm/recipes:gpt2",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/status",
        "@cuda//:cuda_runtime",
        "@googletest//:gtest_main",
    ],
)

cc_binary(
    name = "memorize_general_facts",
    srcs = ["memorize_general_facts.cc"],
    deps = [
        ":dataset",
        ":gradient_clipper",
        ":predictions",
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/dataset",
        "//src/dataset:gpt2_tokenizer",
        "//src/llm:optimizer",
        "//src/llm:batch_validation",
        "//src/llm:checkpoint",
        "//src/llm:cross_entropy_loss",
        "//src/llm:layer",
        "//src/llm/recipes:gpt2",
        "//src/util:status_macros",
        "//src/util:tee_stream",
        "@abseil-cpp//absl/time",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@cuda//:cuda_runtime",
    ],
)

cuda_library(
    name = "gradient_clipper",
    srcs = ["gradient_clipper.cc"],
    hdrs = ["gradient_clipper.h"],
    copts = ["-std=c++20"],
    host_copts = ["-std=c++20"],
    deps = [
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/llm:layer",
        "//src/util:status_macros",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/memory",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@cuda//:cuda_runtime",
    ],
)

cc_test(
    name = "gradient_clipper_test",
    srcs = ["gradient_clipper_test.cc"],
    tags = ["requires-gpu"],
    deps = [
        ":gradient_clipper",
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/llm:layer",
        "//src/util:status_macros",
        "@abseil-cpp//absl/memory",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/types:span",
        "@cuda//:cuda_runtime",
        "@googletest//:gtest_main",
    ],
)
