load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "generation",
    srcs = ["generation.cc"],
    hdrs = ["generation.h"],
    deps = [
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/llm:extract_top1_ids",
        "//src/llm:layer",
        "//src/util:status_macros",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/types:span",
        "@cuda//:cuda_runtime",
    ],
)

cc_test(
    name = "generation_test",
    srcs = ["generation_test.cc"],
    tags = ["requires-gpu"],
    deps = [
        ":generation",
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/llm:layer",
        "//src/util:status_macros",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/types:span",
        "@cuda//:cuda_runtime",
        "@googletest//:gtest_main",
    ],
)

cc_binary(
    name = "memorize_general_facts",
    srcs = ["memorize_general_facts.cc"],
    deps = [
        ":generation",
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/dataset",
        "//src/dataset:compact_vocabulary",
        "//src/dataset:gpt2_detokenizer",
        "//src/dataset:gpt2_tokenizer",
        "//src/dataset:padded_line_dataset",
        "//src/dataset:tokenizer",
        "//src/llm:optimizer",
        "//src/llm:batch_validation",
        "//src/llm:checkpoint",
        "//src/llm:cross_entropy_loss",
        "//src/llm:extract_top1_ids",
        "//src/llm:gradient_clipper",
        "//src/llm:layer",
        "//src/llm/experiments/shakespeare:gpt2",
        "//src/util:status_macros",
        "//src/util:tee_stream",
        "@abseil-cpp//absl/time",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@cuda//:cuda_runtime",
    ],
)
