load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "trace",
    srcs = ["trace.cc"],
    hdrs = ["trace.h"],
    deps = [
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/llm:layer",
        "//src/llm:layer_hooks",
        "//src/util:status_macros",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/types:span",
        "@cuda//:cuda_runtime",
    ],
)

cc_test(
    name = "trace_test",
    srcs = ["trace_test.cc"],
    tags = ["requires-gpu"],
    deps = [
        ":trace",
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/llm:gpt2",
        "//src/llm:layer",
        "//src/llm:layer_hooks",
        "//src/util:status_macros",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/types:span",
        "@cuda//:cuda_runtime",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "report",
    srcs = ["report.cc"],
    hdrs = ["report.h"],
    deps = [
        ":trace",
        "//src/llm:layer",
        "//src/util:status_macros",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "report_test",
    size = "small",
    srcs = ["report_test.cc"],
    deps = [
        ":report",
        ":trace",
        "//src/llm:layer",
        "@abseil-cpp//absl/status",
        "@googletest//:gtest_main",
    ],
)

cc_binary(
    name = "completion_trace",
    srcs = ["completion_trace.cc"],
    deps = [
        ":report",
        ":trace",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/dataset",
        "//src/dataset:compact_vocabulary",
        "//src/dataset:gpt2_detokenizer",
        "//src/dataset:gpt2_tokenizer",
        "//src/llm:checkpoint",
        "//src/llm:generate_greedy_continuation",
        "//src/llm:gpt2",
        "//src/util:status_macros",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
        "@cuda//:cuda_runtime",
    ],
)
