load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("@rules_cuda//cuda:defs.bzl", "cuda_library")

cc_library(
    name = "graph",
    srcs = ["graph.cc"],
    hdrs = ["graph.h"],
    deps = [
        "//src/util:status_macros",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_library(
    name = "history",
    srcs = ["history.cc"],
    hdrs = ["history.h"],
    deps = [
        ":graph",
        "//src/util:status_macros",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/types:span",
    ],
)

cuda_library(
    name = "top_transitions",
    srcs = ["top_transitions.cc"],
    hdrs = ["top_transitions.h"],
    copts = ["--enable-tile", "-std=c++20"],
    host_copts = ["-std=c++20"],
    deps = [
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@cuda//:cuda_runtime",
    ],
)

cc_library(
    name = "model",
    srcs = ["model.cc"],
    hdrs = ["model.h"],
    deps = [
        ":top_transitions",
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/llm:combinators",
        "//src/llm:embedding",
        "//src/llm:fully_connected",
        "//src/llm:gelu",
        "//src/llm:layer",
        "//src/llm:norm",
        "//src/llm:gpt2",
        "//src/util:status_macros",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/functional:function_ref",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@cuda//:cuda_runtime",
    ],
)

cc_binary(
    name = "mlp_automaton",
    srcs = ["mlp_automaton.cc"],
    deps = [
        ":graph",
        ":history",
        ":model",
        "//src/cuda:thread_pool",
        "//src/dataset:dataset",
        "//src/dataset:gpt2_detokenizer",
        "//src/util:status_macros",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "graph_test",
    size = "small",
    srcs = ["graph_test.cc"],
    deps = [
        ":graph",
        "@abseil-cpp//absl/status",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "top_transitions_test",
    size = "small",
    srcs = ["top_transitions_test.cc"],
    tags = ["requires-gpu"],
    deps = [
        ":top_transitions",
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "@abseil-cpp//absl/status",
        "@cuda//:cuda_runtime",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "model_test",
    size = "medium",
    srcs = ["model_test.cc"],
    tags = ["requires-gpu"],
    deps = [
        ":model",
        ":top_transitions",
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/cuda:thread_pool",
        "//src/host:buffer",
        "//src/llm:layer",
        "//src/llm:layer_reference_test_util",
        "//src/llm:layer_references",
        "//src/util:status_macros",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/types:span",
        "@cuda//:cuda_runtime",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "history_test",
    size = "small",
    srcs = ["history_test.cc"],
    deps = [
        ":graph",
        ":history",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/types:span",
        "@googletest//:gtest_main",
    ],
)
