load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "gpt2_model",
    srcs = ["gpt2_model.cc"],
    hdrs = ["gpt2_model.h"],
    visibility = ["//src/tokenizer:__pkg__"],
    deps = [
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/synchronization",
    ],
)

cc_library(
    name = "tokenizer",
    srcs = ["tokenizer.cc"],
    hdrs = ["tokenizer.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":gpt2_model",
        "@abseil-cpp//absl/base:core_headers",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/synchronization",
        "@re2//:re2",
    ],
)

cc_library(
    name = "detokenizer",
    srcs = ["detokenizer.cc"],
    hdrs = ["detokenizer.h"],
    visibility = ["//visibility:public"],
    deps = [
        ":gpt2_model",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/types:span",
    ],
)

cc_test(
    name = "tokenizer_test",
    size = "small",
    srcs = ["tokenizer_test.cc"],
    tags = ["requires-tokenizer"],
    deps = [
        ":detokenizer",
        ":tokenizer",
        "@googletest//:gtest_main",
    ],
)
