load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cuda//cuda:defs.bzl", "cuda_test")

cc_binary(
    name = "hello",
    srcs = ["main.cc"],
    deps = ["@abseil-cpp//absl/strings:str_format"],
)

cuda_test(
    name = "cuda_test",
    size = "small",
    srcs = ["cuda_test.cc"],
    tags = ["requires-gpu"],
    deps = ["//src/cuda:page_locked_host_array"],
)
