#!/usr/bin/env python3
"""Emit a standalone, exact integer network as ordinary split C++ sources.

Production tables cannot access the independently linked verifier's expected
tokens. The optional text encoder contains input-prefix encodings only. Output
publication is atomic, refuses existing destinations, and has no absolute paths.
"""

import ctypes
import hashlib
import json
import os
from pathlib import Path
import re
import tempfile


RUNTIME = "src/llm/experiments/memorize_general_facts/discretized_model/runtime.h"
PACKAGE = "//src/llm/experiments/memorize_general_facts/discretized_model"
NAMESPACE = "pluto::llm::discretized"


def _integer(value, label, minimum=0, maximum=2**32 - 1):
    if type(value) is not int or not minimum <= value <= maximum:
        raise ValueError(f"{label} must be an integer in [{minimum}, {maximum}]")
    return value


def _validate(model):
    if type(model) is not dict or model.get("schema") != 1:
        raise ValueError("expected integer model schema 1")
    layers = _integer(model["layers"], "layers", maximum=1024)
    width = _integer(model["width"], "width", minimum=1)
    vocabulary_size = _integer(model["vocab_size"], "vocab_size", minimum=1, maximum=2**31-1)
    prompt = _integer(model["prompt_tokens"], "prompt_tokens", minimum=1, maximum=1024)
    _integer(model["eos_token"], "eos_token", maximum=vocabulary_size-1)
    vocabulary = model["vocabulary"]
    if len(vocabulary) != vocabulary_size:
        raise ValueError("vocabulary size disagrees with metadata")
    originals = set()
    for row in vocabulary:
        original = _integer(row["original_id"], "original_id", maximum=2**31-1)
        if original in originals:
            raise ValueError("duplicate original vocabulary ID")
        originals.add(original)
        if not isinstance(row["hex"], str) or re.fullmatch(r"(?:[0-9a-f]{2})+", row["hex"]) is None:
            raise ValueError("vocabulary bytes require nonempty canonical lowercase hex")
    states = {}
    for row in model["states"]:
        state = _integer(row["id"], "state ID", minimum=vocabulary_size)
        stage = _integer(row["stage"], "stage", maximum=2*layers)
        if state in states:
            raise ValueError("duplicate state ID")
        if len(row["bits"]) != width:
            raise ValueError("state width differs from model width")
        for bits in row["bits"]:
            _integer(bits, "state bits", maximum=65535)
        states[state] = stage

    def state_at(state, stage):
        _integer(state, "referenced state", minimum=vocabulary_size)
        if states.get(state) != stage:
            raise ValueError(f"state {state} does not belong to stage {stage}")

    entries = set()
    for token, position, state in model["entry"]:
        _integer(token, "entry token", maximum=vocabulary_size-1)
        _integer(position, "entry position", maximum=1023)
        if (token, position) in entries:
            raise ValueError("duplicate entry key")
        entries.add((token, position))
        state_at(state, 0)
    if not entries or len(model["attention"]) != layers or len(model["mlp"]) != layers:
        raise ValueError("missing entry table or wrong block count")
    for block in range(layers):
        keys = set()
        for prefix, output in model["attention"][block]:
            if not 1 <= len(prefix) <= 1024 or tuple(prefix) in keys:
                raise ValueError("invalid or duplicate attention history")
            keys.add(tuple(prefix))
            for state in prefix:
                state_at(state, 2*block)
            state_at(output, 2*block+1)
        keys = set()
        for key, output in model["mlp"][block]:
            if key in keys:
                raise ValueError("duplicate MLP key")
            keys.add(key)
            state_at(key, 2*block+1)
            state_at(output, 2*block+2)
    snaps = set()
    for key, output in model["snap"]:
        if key in snaps:
            raise ValueError("duplicate snap key")
        snaps.add(key)
        state_at(key, 2*layers)
        _integer(output, "snap token", maximum=vocabulary_size-1)
    if not snaps or not model["samples"]:
        raise ValueError("missing readout or verification samples")
    for sample in model["samples"]:
        if not prompt <= len(sample["tokens"]) < 1024:
            raise ValueError("verification sample cannot fit prompt and EOS")
        for token in sample["tokens"]:
            _integer(token, "sample token", maximum=vocabulary_size-1)


def _literal(data):
    return '"' + "".join(f"\\x{byte:02x}" for byte in data) + '"'


def _source(body, header='"tables.h"'):
    return f"// Generated by discretize_emit.py; do not edit.\n#include {header}\n\nnamespace {NAMESPACE} {{\n{body}\n}}  // namespace {NAMESPACE}\n"


def _array(typename, name, rows):
    rows = list(rows)
    # No zero-length arrays: a dummy is never exposed by the returned span.
    return f"const {typename} {name}[] = {{\n" + "".join(f"  {row},\n" for row in (rows or ["{}"])) + "};\n"


def _span(name, count):
    return f"{{{name}, {count}}}"


def _state_source(name, rows):
    rows = sorted(rows)
    body = "namespace {\n" + _array("StateRow", "kRows", (f"{{{a}, {b}}}" for a, b in rows)) + "}\n"
    return _source(body + f"StateTable {name}() {{ return {{{_span('kRows', len(rows))}}}; }}\n")


def _render(model):
    layers = model["layers"]
    declarations = ["absl::Span<const EntryRow> GeneratedEntry();", "absl::Span<const VocabularyRow> GeneratedVocabulary();", "StateTable GeneratedSnap();"]
    for block in range(layers):
        declarations += [f"AttentionTable GeneratedAttention{block}();", f"StateTable GeneratedMlp{block}();"]
    files = {"tables.h": f'// Generated declarations.\n#pragma once\n#include "{RUNTIME}"\nnamespace {NAMESPACE} {{\n' + "\n".join(declarations) + f"\n}}  // namespace {NAMESPACE}\n"}
    entry = sorted(model["entry"])
    body = "namespace {\n" + _array("EntryRow", "kRows", (f"{{{a}, {b}, {c}}}" for a, b, c in entry)) + "}\n"
    files["entry.cc"] = _source(body + f"absl::Span<const EntryRow> GeneratedEntry() {{ return {_span('kRows', len(entry))}; }}")
    vocab = model["vocabulary"]
    body = "namespace {\n" + _array("VocabularyRow", "kRows", (
        f"{{{row['original_id']}, {{{_literal(bytes.fromhex(row['hex']))}, {len(row['hex'])//2}}}}}" for row in vocab)) + "}\n"
    files["vocabulary.cc"] = _source(body + f"absl::Span<const VocabularyRow> GeneratedVocabulary() {{ return {_span('kRows', len(vocab))}; }}")
    for block in range(layers):
        keys, rows = [], []
        for prefix, output in sorted(model["attention"][block]):
            rows.append(f"{{{len(keys)}, {len(prefix)}, {output}}}")
            keys.extend(prefix)
        body = "namespace {\n" + _array("StateId", "kKeys", map(str, keys)) + _array("AttentionRow", "kRows", rows) + "}\n"
        files[f"attention_{block}.cc"] = _source(body + f"AttentionTable GeneratedAttention{block}() {{ return {{{_span('kKeys', len(keys))}, {_span('kRows', len(rows))}}}; }}")
        files[f"mlp_{block}.cc"] = _state_source(f"GeneratedMlp{block}", model["mlp"][block])
    files["snap.cc"] = _state_source("GeneratedSnap", model["snap"])
    body = "const Model& GeneratedModel() {\n"
    body += "  static " + _array("AttentionTable", "kAttention", (f"GeneratedAttention{i}()" for i in range(layers)))
    body += "  static " + _array("StateTable", "kMlp", (f"GeneratedMlp{i}()" for i in range(layers)))
    body += f"  static const Model model{{1024, {model['prompt_tokens']}, {model['eos_token']}, GeneratedVocabulary(), GeneratedEntry(), {_span('kAttention', layers)}, {_span('kMlp', layers)}, GeneratedSnap()}};\n  return model;\n}}"
    files["model.cc"] = _source(body)
    files["prompt_encoder.cc"] = _render_encoder(model)
    files["verification.cc"] = _render_verification(model)
    files["generated_model_test.cc"] = f'''#include <sstream>
#include "{RUNTIME}"
#include "gtest/gtest.h"
namespace {NAMESPACE} {{
absl::Status VerifyGeneratedModel(const Model&, std::ostream&);
TEST(GeneratedIntegerModel, IndependentAutoregressiveCorpusVerification) {{
  const auto& model = GeneratedModel();
  ASSERT_TRUE(ValidateModel(model).ok());
  std::ostringstream report;
  auto result = VerifyGeneratedModel(model, report);
  EXPECT_TRUE(result.ok()) << result << "\\n" << report.str();
}}
}}  // namespace {NAMESPACE}
'''
    files["BUILD.bazel"] = _render_build(layers)
    manifest = {
        "schema": 1, "generator": "discretize_emit.py", "layers": layers,
        "states": len(model["states"]), "vocabulary_size": model["vocab_size"],
        "samples": len(model["samples"]), "scored_targets": sum(len(row["tokens"])-model["prompt_tokens"]+1 for row in model["samples"]),
        "integer_only_inference": True, "expected_tokens_target": "verification",
        "files": {name: hashlib.sha256(value.encode()).hexdigest() for name, value in sorted(files.items())},
    }
    files["manifest.json"] = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    return files, manifest


def _render_encoder(model):
    prefixes = {}
    for sample in model["samples"]:
        text = b""
        for position, token in enumerate(sample["tokens"]):
            text += bytes.fromhex(model["vocabulary"][token]["hex"])
            ids = tuple(sample["tokens"][:position+1])
            if text in prefixes and prefixes[text] != ids:
                raise ValueError("ambiguous captured text-prefix encoding")
            prefixes[text] = ids
    tokens, rows = [], []
    for text, ids in sorted(prefixes.items()):
        rows.append(f"{{{{{_literal(text)}, {len(text)}}}, {len(tokens)}, {len(ids)}}}")
        tokens.extend(ids)
    body = "namespace {\nstruct PromptRow { absl::string_view text; size_t offset; size_t length; };\n"
    body += _array("TokenId", "kTokens", map(str, tokens)) + _array("PromptRow", "kPrompts", rows) + "}\n"
    body += f'''absl::StatusOr<std::vector<TokenId>> EncodeGeneratedPrompt(absl::string_view text) {{
  auto row = std::lower_bound(std::begin(kPrompts), std::end(kPrompts), text,
      [](const PromptRow& r, absl::string_view key) {{ return r.text < key; }});
  if (row == std::end(kPrompts) || row->text != text)
    return absl::NotFoundError("unsupported text encoding: use a captured corpus prefix at a token boundary, or --token_ids");
  return std::vector<TokenId>(kTokens + row->offset, kTokens + row->offset + row->length);
}}'''
    return '#include <algorithm>\n#include <iterator>\n' + _source(body, f'"{RUNTIME}"')


def _render_verification(model):
    tokens, rows = [], []
    for sample in model["samples"]:
        rows.append(f"{{{len(tokens)}, {len(sample['tokens'])}}}")
        tokens.extend(sample["tokens"])
    body = "namespace {\nstruct Sample { size_t offset; size_t length; };\n"
    body += _array("TokenId", "kExpectedTokens", map(str, tokens)) + _array("Sample", "kSamples", rows) + "}\n"
    body += '''absl::Status VerifyGeneratedModel(const Model& model, std::ostream& output) {
  size_t targets = 0;
  size_t sentences = 0;
  for (const auto& sample : kSamples) {
    const auto original = absl::MakeConstSpan(kExpectedTokens + sample.offset, sample.length);
    auto generated = Generate(model, original.first(model.prompt_tokens),
                              sample.length - model.prompt_tokens + 1);
    if (!generated.ok()) return generated.status();
    std::vector<TokenId> expected(original.begin() + model.prompt_tokens, original.end());
    expected.push_back(model.eos_token);
    if (*generated != expected) {
      output << "mismatch at verification sentence " << sentences + 1 << "\\n";
      return absl::DataLossError("integer autoregressive completion differs from independent fixture");
    }
    targets += expected.size();
    ++sentences;
  }
  output << "errors=0/" << targets << " exact_sentences=" << sentences << "/" << sentences
         << " eos=" << sentences << " autoregressive=true integer_only=true\\n";
  return absl::OkStatus();
}'''
    return '#include <ostream>\n' + _source(body, f'"{RUNTIME}"')


def _render_build(layers):
    sources = ["entry.cc", "model.cc", "snap.cc", "vocabulary.cc"]
    sources += [f"attention_{i}.cc" for i in range(layers)]
    sources += [f"mlp_{i}.cc" for i in range(layers)]
    source_text = "\n".join(f'        "{name}",' for name in sorted(sources))
    return f'''# Generated ordinary C++ targets; no build-time generation or GPU dependency.
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

cc_library(
    name = "model",
    srcs = [
{source_text}
    ],
    hdrs = ["tables.h"],
    visibility = ["//visibility:public"],
    deps = ["{PACKAGE}:runtime"],
)
cc_library(
    name = "prompt_encoder",
    srcs = ["prompt_encoder.cc"],
    deps = ["{PACKAGE}:runtime"],
)
cc_library(
    name = "verification",
    srcs = ["verification.cc"],
    deps = ["{PACKAGE}:runtime"],
)
cc_binary(
    name = "discretized_model",
    srcs = ["{PACKAGE}:main.cc"],
    deps = [":model", ":prompt_encoder", ":verification", "{PACKAGE}:runtime"],
)
cc_test(
    name = "generated_model_test",
    srcs = ["generated_model_test.cc"],
    deps = [":model", ":verification", "{PACKAGE}:runtime", "@googletest//:gtest_main"],
)
'''


def _publish(staging, destination):
    rename = ctypes.CDLL(None, use_errno=True).renameat2
    rename.argtypes = (ctypes.c_int, ctypes.c_char_p, ctypes.c_int, ctypes.c_char_p, ctypes.c_uint)
    rename.restype = ctypes.c_int
    if rename(-100, os.fsencode(staging), -100, os.fsencode(destination), 1):
        code = ctypes.get_errno()
        raise OSError(code, os.strerror(code), str(destination))


def emit_model(model, output_dir):
    """Validate and atomically emit into a fresh directory; return manifest."""
    _validate(model)
    files, manifest = _render(model)
    destination = Path(output_dir)
    if not destination.name or destination.name in (".", ".."):
        raise ValueError("output must name a fresh directory")
    destination = destination.parent.resolve(strict=True) / destination.name
    if destination.exists() or destination.is_symlink():
        raise FileExistsError(f"refusing existing generated output: {destination}")
    with tempfile.TemporaryDirectory(prefix=f".{destination.name}.emit-", dir=destination.parent) as temporary:
        staging = Path(temporary)
        for name, contents in sorted(files.items()):
            with (staging / name).open("x", encoding="utf-8", newline="\n") as output:
                output.write(contents)
                output.flush()
                os.fsync(output.fileno())
        _publish(staging, destination)
    return manifest
