load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("@rules_cuda//cuda:defs.bzl", "cuda_library")

cuda_library(
    name = "readout",
    srcs = ["readout.cc"],
    hdrs = ["readout.h"],
    copts = ["--enable-tile", "-std=c++20"],
    host_copts = ["-std=c++20"],
    deps = [
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/llm:vocabulary_readout",
        "//src/llm/experiments/shakespeare:gpt2",
        "//src/util:status_macros",
        "@abseil-cpp//absl/memory",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@cuda//:cuda_runtime",
    ],
)

cc_binary(
    name = "kvq_explorer",
    srcs = ["kvq_explorer.cc"],
    deps = [
        ":readout",
        "//src/dataset:gpt2_detokenizer",
        "//src/dataset:gpt2_tokenizer",
        "//src/util:status_macros",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/flags:parse",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/strings",
    ],
)

cc_test(
    name = "readout_test",
    size = "medium",
    srcs = ["readout_test.cc"],
    tags = ["requires-gpu"],
    deps = [
        ":readout",
        "//src/cuda:buffer",
        "//src/cuda:executor",
        "//src/cuda:page_locked_host_array",
        "//src/util:status_macros",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/types:span",
        "@cuda//:cuda_runtime",
        "@googletest//:gtest_main",
    ],
)
